using Microsoft.CodeAnalysis;
using Sentinel.Diagnostics.Generator.Metadata;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Text;

namespace Sentinel.Diagnostics.Generator.Emitters;

/// <summary>
/// Generates shared diagnostic infrastructure consumed by generated
/// Sentinel Diagnostics wrappers and policies.
///
/// This emitter performs no semantic analysis and does not inspect
/// attributes. It consumes finalized generator metadata only.
/// </summary>
internal static class DiagnosticsEmitter
{
    private const string HintName =
        "SentinelDiagnostics.Infrastructure.g.cs";

    /// <summary>
    /// Emits the shared Sentinel Diagnostics infrastructure.
    ///
    /// The complete metadata collection is used to generate immutable
    /// lookup information for methods, policies, spans, and parameters.
    /// </summary>
    /// <param name="context">
    /// The source production context.
    /// </param>
    /// <param name="methods">
    /// Finalized method generation metadata.
    /// </param>
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<SentinelMethodGenerationMetadata> methods)
    {
        string source =
            GenerateSource(methods);

        context.AddSource(
            HintName,
            source);
    }

    /// <summary>
    /// Generates the complete diagnostic infrastructure source.
    /// </summary>
    private static string GenerateSource(
        ImmutableArray<SentinelMethodGenerationMetadata> methods)
    {
        var source =
            new StringBuilder();

        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();

        source.AppendLine(
            "using System;");

        source.AppendLine(
            "using System.Diagnostics;");

        source.AppendLine();

        source.AppendLine(
            "namespace Sentinel.Diagnostics.Generated.Diagnostics;");

        source.AppendLine();

        GenerateSentinelDiagnostics(
            source,
            methods);

        source.AppendLine();

        GenerateSentinelDiagnosticPolicy(
            source);

        return source.ToString();
    }

    /// <summary>
    /// Generates the primary static diagnostics helper.
    /// </summary>
    private static void GenerateSentinelDiagnostics(
        StringBuilder source,
        ImmutableArray<SentinelMethodGenerationMetadata> methods)
    {
        source.AppendLine(
            "/// <summary>");

        source.AppendLine(
            "/// Shared diagnostic helpers generated by Sentinel Diagnostics.");

        source.AppendLine(
            "/// </summary>");

        source.AppendLine(
            "internal static class SentinelDiagnostics");

        source.AppendLine("{");

        GenerateLogStart(source);

        source.AppendLine();

        GenerateLogEnd(source);

        source.AppendLine();

        GenerateLogParameter(source, methods);

        source.AppendLine();

        GenerateShouldLogParameter(source, methods);

        source.AppendLine();

        GenerateIsSensitiveParameter(source, methods);

        source.AppendLine();

        GenerateStartSpan(source);

        source.AppendLine();

        GenerateGetSpanName(source, methods);

        source.AppendLine();

        GenerateGetPolicyName(source, methods);

        source.AppendLine("}");
    }

    /// <summary>
    /// Generates the method-start logging helper.
    /// </summary>
    private static void GenerateLogStart(
        StringBuilder source)
    {
        source.AppendLine(
            "    internal static void LogStart(");

        source.AppendLine(
            "        string methodName,");

        source.AppendLine(
            "        string spanName,");

        source.AppendLine(
            "        string? policyName)");

        source.AppendLine("    {");

        source.AppendLine(
            "        Trace.WriteLine(");

        source.AppendLine(
            "            $\"Sentinel Start: {methodName} " +
            "Span={spanName} Policy={policyName}\");");

        source.AppendLine(
            "    }");
    }

    /// <summary>
    /// Generates the method-end logging helper.
    /// </summary>
    private static void GenerateLogEnd(
        StringBuilder source)
    {
        source.AppendLine(
            "    internal static void LogEnd(");

        source.AppendLine(
            "        string methodName)");

        source.AppendLine("    {");

        source.AppendLine(
            "        Trace.WriteLine(");

        source.AppendLine(
            "            $\"Sentinel End: {methodName}\");");

        source.AppendLine(
            "    }");
    }

    /// <summary>
    /// Generates the parameter logging helper.
    ///
    /// The helper itself enforces the generated parameter policy, so
    /// callers cannot accidentally log a parameter marked sensitive
    /// or configured with ShouldLog=false.
    /// </summary>
    private static void GenerateLogParameter(
        StringBuilder source,
        ImmutableArray<SentinelMethodGenerationMetadata> methods)
    {
        source.AppendLine(
            "    internal static void LogParameter(");

        source.AppendLine(
            "        string methodName,");

        source.AppendLine(
            "        string parameterName,");

        source.AppendLine(
            "        object? value)");

        source.AppendLine("    {");

        source.AppendLine(
            "        if (!ShouldLogParameter(");

        source.AppendLine(
            "                methodName,");

        source.AppendLine(
            "                parameterName))");

        source.AppendLine(
            "        {");

        source.AppendLine(
            "            return;");

        source.AppendLine(
            "        }");

        source.AppendLine();

        source.AppendLine(
            "        Trace.WriteLine(");

        source.AppendLine(
            "            $\"Sentinel Parameter: " +
            "{methodName}.{parameterName}={value}\");");

        source.AppendLine(
            "    }");
    }

    /// <summary>
    /// Generates the parameter logging policy lookup.
    /// </summary>
    private static void GenerateShouldLogParameter(
        StringBuilder source,
        ImmutableArray<SentinelMethodGenerationMetadata> methods)
    {
        source.AppendLine(
            "    internal static bool ShouldLogParameter(");

        source.AppendLine(
            "        string methodName,");

        source.AppendLine(
            "        string parameterName)");

        source.AppendLine("    {");

        source.AppendLine(
            "        return methodName switch");

        source.AppendLine(
            "        {");

        foreach (SentinelMethodGenerationMetadata method
                 in methods)
        {
            foreach (SentinelParameterGenerationMetadata parameter
                     in method.Parameters)
            {
                source.Append("            \"");
                source.Append(
                    EscapeString(method.FullyQualifiedMethodName));
                source.Append('.');
                source.Append(
                    EscapeString(parameter.Name));
                source.Append("\" => ");

                source.Append(
                    parameter.ShouldLog &&
                    !parameter.IsSensitive
                        ? "true"
                        : "false");

                source.AppendLine(",");
            }
        }

        source.AppendLine(
            "            _ => false");

        source.AppendLine(
            "        };");

        source.AppendLine(
            "    }");
    }

    /// <summary>
    /// Generates the parameter sensitivity lookup.
    /// </summary>
    private static void GenerateIsSensitiveParameter(
        StringBuilder source,
        ImmutableArray<SentinelMethodGenerationMetadata> methods)
    {
        source.AppendLine(
            "    internal static bool IsSensitiveParameter(");

        source.AppendLine(
            "        string methodName,");

        source.AppendLine(
            "        string parameterName)");

        source.AppendLine("    {");

        source.AppendLine(
            "        return methodName switch");

        source.AppendLine(
            "        {");

        foreach (SentinelMethodGenerationMetadata method
                 in methods)
        {
            foreach (SentinelParameterGenerationMetadata parameter
                     in method.Parameters)
            {
                if (!parameter.IsSensitive)
                {
                    continue;
                }

                source.Append("            \"");
                source.Append(
                    EscapeString(method.FullyQualifiedMethodName));
                source.Append('.');
                source.Append(
                    EscapeString(parameter.Name));
                source.AppendLine("\" => true,");
            }
        }

        source.AppendLine(
            "            _ => false");

        source.AppendLine(
            "        };");

        source.AppendLine(
            "    }");
    }

    /// <summary>
    /// Generates the OpenTelemetry Activity span helper.
    ///
    /// The generated ActivitySource is immutable and safe for concurrent
    /// use. ActivitySource itself is designed for concurrent application
    /// use.
    /// </summary>
    private static void GenerateStartSpan(
        StringBuilder source)
    {
        source.AppendLine(
            "    private static readonly ActivitySource " +
            "ActivitySource =");

        source.AppendLine(
            "        new(\"Sentinel.Diagnostics\");");

        source.AppendLine();

        source.AppendLine(
            "    internal static Activity? StartSpan(");

        source.AppendLine(
            "        string spanName)");

        source.AppendLine("    {");

        source.AppendLine(
            "        return ActivitySource.StartActivity(");

        source.AppendLine(
            "            spanName);");

        source.AppendLine(
            "    }");
    }

    /// <summary>
    /// Generates the span-name lookup.
    /// </summary>
    private static void GenerateGetSpanName(
        StringBuilder source,
        ImmutableArray<SentinelMethodGenerationMetadata> methods)
    {
        source.AppendLine(
            "    internal static string GetSpanName(");

        source.AppendLine(
            "        string methodName)");

        source.AppendLine("    {");

        source.AppendLine(
            "        return methodName switch");

        source.AppendLine(
            "        {");

        foreach (SentinelMethodGenerationMetadata method
                 in methods)
        {
            source.Append("            \"");
            source.Append(
                EscapeString(method.FullyQualifiedMethodName));
            source.Append("\" => \"");
            source.Append(
                EscapeString(method.SpanName));
            source.AppendLine("\",");
        }

        source.AppendLine(
            "            _ => methodName");

        source.AppendLine(
            "        };");

        source.AppendLine(
            "    }");
    }

    /// <summary>
    /// Generates the policy-name lookup.
    /// </summary>
    private static void GenerateGetPolicyName(
        StringBuilder source,
        ImmutableArray<SentinelMethodGenerationMetadata> methods)
    {
        source.AppendLine(
            "    internal static string? GetPolicyName(");

        source.AppendLine(
            "        string methodName)");

        source.AppendLine("    {");

        source.AppendLine(
            "        return methodName switch");

        source.AppendLine(
            "        {");

        foreach (SentinelMethodGenerationMetadata method
                 in methods)
        {
            source.Append("            \"");
            source.Append(
                EscapeString(method.FullyQualifiedMethodName));
            source.Append("\" => ");

            if (method.PolicyName is null)
            {
                source.AppendLine("null,");
            }
            else
            {
                source.Append('\"');
                source.Append(
                    EscapeString(method.PolicyName));
                source.AppendLine("\",");
            }
        }

        source.AppendLine(
            "            _ => null");

        source.AppendLine(
            "        };");

        source.AppendLine(
            "    }");
    }

    /// <summary>
    /// Generates the policy helper.
    /// </summary>
    private static void GenerateSentinelDiagnosticPolicy(
        StringBuilder source)
    {
        source.AppendLine(
            "/// <summary>");

        source.AppendLine(
            "/// Immutable policy lookup helpers generated by " +
            "Sentinel Diagnostics.");

        source.AppendLine(
            "/// </summary>");

        source.AppendLine(
            "internal static class SentinelDiagnosticPolicy");

        source.AppendLine("{");

        source.AppendLine(
            "    internal static bool IsLoggingAllowed(");

        source.AppendLine(
            "        string methodName,");

        source.AppendLine(
            "        string parameterName)");

        source.AppendLine("    {");

        source.AppendLine(
            "        return SentinelDiagnostics.ShouldLogParameter(");

        source.AppendLine(
            "            methodName,");

        source.AppendLine(
            "            parameterName);");

        source.AppendLine(
            "    }");

        source.AppendLine("}");
    }

    /// <summary>
    /// Escapes a string for use as a generated C# string literal.
    /// </summary>
    private static string EscapeString(
        string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }

    internal static void LogParameter(
        string methodName,
        string parameterName,
        object? value)
    {
        if (!ShouldLogParameter(methodName, parameterName))
        {
            return;
        }

        Trace.WriteLine(
            $"Sentinel Parameter: {methodName}.{parameterName}={value}");
    }

    internal static bool ShouldLogParameter(
        string methodName,
        string parameterName)
    {
        return (methodName, parameterName) switch
        {
            ("global::MyApp.CustomerService.GetCustomer", "customerId") => true,
            _ => false
        };
    }
}