<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>

    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Emitters\**" />
    <EmbeddedResource Remove="Emitters\**" />
    <None Remove="Emitters\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Builders\MetadataBuilder.cs.old" />
    <None Remove="Configuration\ClassAutoLogOptions.cs.old" />
    <None Remove="Metadata\ContainingTypeMetadata.cs.old" />
    <None Remove="Metadata\RawParameterMetadata.cs.old" />
    <None Remove="Metadata\SentinelMethodGenerationMetadata.cs.old" />
    <None Remove="Metadata\SentinelParameterGenerationMetadata.cs.old" />
    <None Remove="Validation\MetadataValidator.cs.old" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" PrivateAssets="all" />

    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" PrivateAssets="all" />

    <PackageReference Include="System.Text.Json" Version="10.0.11" />
  </ItemGroup>

</Project>