using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Sentinel.Diagnostics.Generator.Metadata;

namespace Sentinel.Diagnostics.Generator.Emitters;

/// <summary>
/// Emits immutable policy classes for each unique AutoLog policy used
/// by the generated methods.
///
/// The Policy Emitter is responsible only for source generation. It does
/// not perform syntax analysis, semantic analysis, metadata extraction,
/// parameter-value gathering, serialization, or wrapper generation.
///
/// Policy classes are stateless and thread-safe. All policy decisions are
/// represented as generated switch expressions rather than mutable runtime
/// collections.
/// </summary>
internal sealed class PolicyEmitter
{
    private const string GeneratedNamespace =
        "Sentinel.Diagnostics.Generated.Policies";

    /// <summary>
    /// Emits one policy class for every unique policy name.
    /// </summary>
    /// <param name="context">
    /// The incremental source production context.
    /// </param>
    /// <param name="methods">
    /// Finalized generation metadata produced by the Metadata Builder.
    /// </param>
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<SentinelMethodGenerationMetadata> methods)
    {
        if (methods.IsDefaultOrEmpty)
        {
            return;
        }

        IEnumerable<IGrouping<string, SentinelMethodGenerationMetadata>>
            policyGroups =
                methods
                    .Where(method =>
                        !string.IsNullOrWhiteSpace(method.PolicyName))
                    .GroupBy(
                        method => method.PolicyName!,
                        StringComparer.Ordinal)
                    .OrderBy(
                        group => group.Key,
                        StringComparer.Ordinal);

        foreach (IGrouping<string, SentinelMethodGenerationMetadata> group
                 in policyGroups)
        {
            string source = GeneratePolicySource(
                group.Key,
                ImmutableArray<SentinelMethodGenerationMetadata>.Empty);

            string hintName =
                $"{SanitizeIdentifier(group.Key)}Policy.g.cs";

            context.AddSource(hintName, source);
        }
    }

    /// <summary>
    /// Generates the source code for a single policy.
    /// </summary>
    private static string GeneratePolicySource(
        string policyName,
        ImmutableArray<SentinelMethodGenerationMetadata> methods)
    {
        var source = new StringBuilder();

        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine($"namespace {GeneratedNamespace};");
        source.AppendLine();

        string className =
            $"{SanitizeIdentifier(policyName)}Policy";

        source.AppendLine(
            $"internal sealed class {className}");
        source.AppendLine("{");

        source.AppendLine(
            $"    public const string Name = {ToLiteral(policyName)};");
        source.AppendLine();

        GenerateGetSpanNameMethod(source, methods);
        GenerateShouldLogParameterMethod(source, methods);
        GenerateIsParameterSensitiveMethod(source, methods);

        source.AppendLine("}");

        return source.ToString();
    }

    /// <summary>
    /// Generates the method that resolves the span name for a method.
    /// </summary>
    private static void GenerateGetSpanNameMethod(
        StringBuilder source,
        ImmutableArray<SentinelMethodGenerationMetadata> methods)
    {
        source.AppendLine(
            "    public static string GetSpanName(string methodName)");
        source.AppendLine("    {");

        source.AppendLine(
            "        if (methodName is null)");
        source.AppendLine("        {");
        source.AppendLine(
            "            throw new System.ArgumentNullException(nameof(methodName));");
        source.AppendLine("        }");
        source.AppendLine();

        source.AppendLine(
            "        return methodName switch");
        source.AppendLine("        {");

        foreach (SentinelMethodGenerationMetadata method in
                 OrderMethods(methods))
        {
            source.AppendLine(
                $"            {ToLiteral(method.FullyQualifiedMethodName)} => " +
                $"{ToLiteral(method.SpanName)},");
        }

        source.AppendLine(
            "            _ => methodName");
        source.AppendLine("        };");

        source.AppendLine("    }");
        source.AppendLine();
    }

    /// <summary>
    /// Generates the method that determines whether a parameter value
    /// may be logged.
    ///
    /// Sensitive parameters are always denied, regardless of ShouldLog.
    /// </summary>
    private static void GenerateShouldLogParameterMethod(
        StringBuilder source,
        ImmutableArray<SentinelMethodGenerationMetadata> methods)
    {
        source.AppendLine(
            "    public static bool ShouldLogParameter(");
        source.AppendLine(
            "        string methodName,");
        source.AppendLine(
            "        string parameterName)");
        source.AppendLine("    {");

        source.AppendLine(
            "        if (methodName is null)");
        source.AppendLine("        {");
        source.AppendLine(
            "            throw new System.ArgumentNullException(nameof(methodName));");
        source.AppendLine("        }");
        source.AppendLine();

        source.AppendLine(
            "        if (parameterName is null)");
        source.AppendLine("        {");
        source.AppendLine(
            "            throw new System.ArgumentNullException(nameof(parameterName));");
        source.AppendLine("        }");
        source.AppendLine();

        source.AppendLine(
            "        return methodName switch");
        source.AppendLine("        {");

        foreach (SentinelMethodGenerationMetadata method in
                 OrderMethods(methods))
        {
            source.AppendLine(
                $"            {ToLiteral(method.FullyQualifiedMethodName)} =>");

            source.AppendLine(
                "                parameterName switch");
            source.AppendLine("                {");

            foreach (SentinelParameterGenerationMetadata parameter in
                     OrderParameters(method.Parameters))
            {
                // Sensitive data always wins over ShouldLog.
                bool shouldLog =
                    parameter.ShouldLog &&
                    !parameter.IsSensitive;

                source.AppendLine(
                    $"                    {ToLiteral(parameter.Name)} => " +
                    $"{ToBooleanLiteral(shouldLog)},");
            }

            source.AppendLine(
                "                    _ => false");
            source.AppendLine("                },");
        }

        // Unknown methods/parameters are denied by default.
        source.AppendLine(
            "            _ => false");
        source.AppendLine("        };");

        source.AppendLine("    }");
        source.AppendLine();
    }

    /// <summary>
    /// Generates the method that identifies sensitive parameters.
    /// </summary>
    private static void GenerateIsParameterSensitiveMethod(
        StringBuilder source,
        ImmutableArray<SentinelMethodGenerationMetadata> methods)
    {
        source.AppendLine(
            "    public static bool IsParameterSensitive(");
        source.AppendLine(
            "        string methodName,");
        source.AppendLine(
            "        string parameterName)");
        source.AppendLine("    {");

        source.AppendLine(
            "        if (methodName is null)");
        source.AppendLine("        {");
        source.AppendLine(
            "            throw new System.ArgumentNullException(nameof(methodName));");
        source.AppendLine("        }");
        source.AppendLine();

        source.AppendLine(
            "        if (parameterName is null)");
        source.AppendLine("        {");
        source.AppendLine(
            "            throw new System.ArgumentNullException(nameof(parameterName));");
        source.AppendLine("        }");
        source.AppendLine();

        source.AppendLine(
            "        return methodName switch");
        source.AppendLine("        {");

        foreach (SentinelMethodGenerationMetadata method in
                 OrderMethods(methods))
        {
            source.AppendLine(
                $"            {ToLiteral(method.FullyQualifiedMethodName)} =>");

            source.AppendLine(
                "                parameterName switch");
            source.AppendLine("                {");

            foreach (SentinelParameterGenerationMetadata parameter in
                     OrderParameters(method.Parameters))
            {
                source.AppendLine(
                    $"                    {ToLiteral(parameter.Name)} => " +
                    $"{ToBooleanLiteral(parameter.IsSensitive)},");
            }

            source.AppendLine(
                "                    _ => false");
            source.AppendLine("                },");
        }

        source.AppendLine(
            "            _ => false");
        source.AppendLine("        };");

        source.AppendLine("    }");
        source.AppendLine();
    }

    /// <summary>
    /// Orders methods deterministically so generated source remains stable
    /// between compilations.
    /// </summary>
    private static IEnumerable<SentinelMethodGenerationMetadata>
        OrderMethods(
            IEnumerable<SentinelMethodGenerationMetadata> methods)
    {
        return methods.OrderBy(
            method => method.FullyQualifiedMethodName,
            StringComparer.Ordinal);
    }

    /// <summary>
    /// Orders parameters deterministically.
    /// </summary>
    private static IEnumerable<SentinelParameterGenerationMetadata>
        OrderParameters(
            IEnumerable<SentinelParameterGenerationMetadata> parameters)
    {
        return parameters.OrderBy(
            parameter => parameter.Name,
            StringComparer.Ordinal);
    }

    /// <summary>
    /// Converts a policy name into a valid C# identifier.
    /// </summary>
    private static string SanitizeIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "Default";
        }

        var result = new StringBuilder(value.Length);

        for (int index = 0; index < value.Length; index++)
        {
            char character = value[index];

            bool valid =
                index == 0
                    ? char.IsLetter(character) || character == '_'
                    : char.IsLetterOrDigit(character) || character == '_';

            result.Append(valid ? character : '_');
        }

        string identifier = result.ToString();

        if (identifier.Length == 0)
        {
            identifier = "Default";
        }

        if (IsCSharpKeyword(identifier))
        {
            identifier = "_" + identifier;
        }

        return identifier;
    }

    /// <summary>
    /// Determines whether a string is a C# keyword or contextual keyword
    /// that should not be used directly as a generated type name.
    /// </summary>
    private static bool IsCSharpKeyword(string value)
    {
        return value switch
        {
            "abstract" or
            "as" or
            "base" or
            "bool" or
            "break" or
            "byte" or
            "case" or
            "catch" or
            "char" or
            "checked" or
            "class" or
            "const" or
            "continue" or
            "decimal" or
            "default" or
            "delegate" or
            "do" or
            "double" or
            "else" or
            "enum" or
            "event" or
            "explicit" or
            "extern" or
            "false" or
            "finally" or
            "fixed" or
            "float" or
            "for" or
            "foreach" or
            "goto" or
            "if" or
            "implicit" or
            "in" or
            "int" or
            "interface" or
            "internal" or
            "is" or
            "lock" or
            "long" or
            "namespace" or
            "new" or
            "null" or
            "object" or
            "operator" or
            "out" or
            "override" or
            "params" or
            "private" or
            "protected" or
            "public" or
            "readonly" or
            "ref" or
            "return" or
            "sbyte" or
            "sealed" or
            "short" or
            "sizeof" or
            "stackalloc" or
            "static" or
            "string" or
            "struct" or
            "switch" or
            "this" or
            "throw" or
            "true" or
            "try" or
            "typeof" or
            "uint" or
            "ulong" or
            "unchecked" or
            "unsafe" or
            "ushort" or
            "using" or
            "virtual" or
            "void" or
            "volatile" or
            "while" or
            "add" or
            "alias" or
            "and" or
            "ascending" or
            "async" or
            "await" or
            "by" or
            "descending" or
            "dynamic" or
            "equals" or
            "file" or
            "from" or
            "get" or
            "global" or
            "group" or
            "init" or
            "into" or
            "join" or
            "let" or
            "managed" or
            "nameof" or
            "nint" or
            "not" or
            "notnull" or
            "on" or
            "or" or
            "orderby" or
            "partial" or
            "record" or
            "remove" or
            "required" or
            "scoped" or
            "select" or
            "set" or
            "unmanaged" or
            "value" or
            "var" or
            "when" or
            "where" or
            "with" or
            "yield" => true,

            _ => false
        };
    }

    private static string ToLiteral(string value)
    {
        return Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(
            value,
            quote: true);
    }

    private static string ToBooleanLiteral(bool value)
    {
        return value ? "true" : "false";
    }
}